version: "3"
services:
  sangoes-uc:
    build:
      context: dockerfile/uc
    restart: always
    image: sangoes:sangoes-uc
    container_name: sangoes-uc
    depends_on:
    - mysql
    - redis
    - rabbit
    environment:
    - spring.profiles.active=test
    - MYSQL_HOST=10.211.55.7
    - MYSQL_PORT=3306
    - REDIS_HOST=10.211.55.7
    - REDIS_PORT=6379
    command: java -Xmx1000m -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    ports:
    - 8080:8080
    networks:
    - net-sangoes
  mysql:
    image: mysql:5.7.23
    restart: always
    container_name: mysql
    ports:
    - "3306:3306"
    volumes:
    - ./dockerfile/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    - /usr/local/docker/mysql/:/var/lib/mysql/:rw
    environment:
      MYSQL_USER: sangoes
      MYSQL_PASSWORD: "Sangoes123456"
      MYSQL_ROOT_PASSWORD: "Sangoes123456"
    networks:
    - net-sangoes
  redis:
    image: redis:4.0.11
    restart: always
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
    - "6379:6379"
    volumes:
    - /usr/local/docker/redis/data:/data
    - ./dockerfile/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
    - net-sangoes
  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    restart: always
    container_name: rabbit
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "15671:15671"
    - "15672:15672"
    environment:
    - RABBITMQ_DEFAULT_USER=sangoes
    - RABBITMQ_DEFAULT_PASS=Sangoes123456
    networks:
    - net-sangoes
networks:
  net-sangoes:
    external: true