version: "3"
services:
  sangoes-uc:
    build:
      context: ./sangoes-uc/src/docker
    restart: always
    image: sangoes/sangoes-uc
    container_name: sangoes-uc
    depends_on:
    - 'redis'
    - 'mysql'
    environment:
    - spring.profiles.active=test
    - MYSQL_HOST=10.211.55.7
    - MYSQL_PORT=3306
    - REDIS_HOST=10.211.55.7
    - REDIS_PORT=6379
    command: java -Xmx1000m -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    ports:
    - 8080:8080
    networks:
    - net-sangoes
networks:
  net-sangoes:
    external: true