# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  servlet:
    context-path: /api
#日志
logging:
  level: debug
  level.sangoes.uc: debug
  path: logs/
  file: sangoes-uc.log
#application
spring:
  profiles:
    active: dev #dev 开发 prod 生产(部署)
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
  freemarker:
    cache: false
    request-context-attribute: request
#mybatis
mybatis:
  #  type-aliases-package: com.sangoes.boot.uc.modules.model
  mapper-locations: classpath:mapper/*.xml
#mapper
mapper:
  #  mappers:
  #  - com.sangoes.boot.uc.util.MyMapper
  not-empty: false
  identity: MYSQL
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#swagger
swagger:
  enabled: true
  title: 用户中心API
  description: 用户中心
  version: 0.1
  license: MIT
  license-url: http://www.sangoes.com
  terms-of-service-url:
  contact:
    name: jerrychir
    email: jerrychir@163.com
    url: http://www.sangoes.com
  base-package: com.sangoes.boot
  base-path: /**
  exclude-path: /error, /ops/**
