
#调试
debug: false

#datasource
spring:
  devtools:
    restart:
      enabled: true #devtools
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/boot?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: sangoes
    password: ENC(myS91HA17JVaJni8nGWPQTH+TnpDYMc6)
    continue-on-error: true
    platform: mysql
#logging
logging:
  level: warn
  level.org.springframework.security: DEBUG
#define
security:
  jwt:
    token:
      secret-key: sangoes-boot #私钥
      expire-length: 3600000 #1小时 过期时间
#忽略请求api
ignore:
  apis:
  - /user/signup
  - /user/signin/mobile
  - /user/signin/account
  - /encrypt/mobile/*
  - /encrypt/rsa/*
  - /captcha/sms/*
  - /captcha/image/*
  # 临时添加
  - /oauth/token

  urls:
  - /v2/api-docs
  - /swagger-resources/**
  - /swagger-ui.html
  - /configuration/**
  - /webjars/**
  - /public